config/routes.rb
Kbase::Application.routes.draw do
  get 'signup', :to => 'users#new', :as => 'signup'
  get 'login', :to => 'sessions#new', :as => 'login'
  get 'logout', :to => 'sessions#destroy', :as => 'logout'

  resources :sessions
  resources :users
  resources :kbs
  root :to => 'kbs#index'
end

app/models/kb.rb
class Kb < ActiveRecord::Base
  def self.search(search)
    if search
      where('upper(tags || title || content) LIKE ?', "%#{search.to_s.upcase}%")
    else
      scoped
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :role, :password, :password_confirmation

  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authenticate
    redirect_to login_path if current_user.nil?
  end

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def is_admin?
      if current_user and current_user.email == 'titasak@gmail.com'
        true
      else
        false
      end
    end

  helper_method :current_user, :is_admin?
end

app/controllers/kbs_controller.rb
class KbsController < ApplicationController
  before_filter :authenticate

  # GET /kbs
  # GET /kbs.json
  def index
    @kbs = Kb.search(params[:q]).page(params[:page]).order("id desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @kbs }
    end
  end

  # GET /kbs/1
  # GET /kbs/1.json
  def show
    @kb = Kb.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @kb }
    end
  end

  # GET /kbs/new
  # GET /kbs/new.json
  def new
    @kb = Kb.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @kb }
    end
  end

  # GET /kbs/1/edit
  def edit
    @kb = Kb.find(params[:id])
  end

  # POST /kbs
  # POST /kbs.json
  def create
    @kb = Kb.new(params[:kb])

    respond_to do |format|
      if @kb.save
        format.html { redirect_to @kb, :notice => 'Kb was successfully created.' }
        format.json { render :json => @kb, :status => :created, :location => @kb }
      else
        format.html { render :action => "new" }
        format.json { render :json => @kb.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /kbs/1
  # PUT /kbs/1.json
  def update
    @kb = Kb.find(params[:id])

    respond_to do |format|
      if @kb.update_attributes(params[:kb])
        format.html { redirect_to @kb, :notice => 'Kb was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @kb.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /kbs/1
  # DELETE /kbs/1.json
  def destroy
    @kb = Kb.find(params[:id])
    @kb.destroy

    respond_to do |format|
      format.html { redirect_to kbs_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, :notice => "Logged in successful!"
    else
      flash.now.alert = "Email or password is invalid!"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged Out successful!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up"
    else
      render "new"
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kbs_helper.rb
module KbsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/kbs/_form.html.erb
<%= simple_form_for @kb, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Kb</legend>

    <%= f.input :tags %>
    <%= f.input :title, :width => '600px;' %>
    <%= f.input :content, 
                :as => :text, 
                :input_html => {:rows => 5, :style => "width:600px"} %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', kbs_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/kbs/index.html.erb
<h1>Notes</h1>

<%= paginate @kbs %>
<p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Tags</th>
      <th>Title</th>
      <th>Content</th>
      <% if is_admin? %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @kbs.each do |kb| %>
      <tr>
        <td><%= link_to kb.id, kb_path(kb) %></td>
        <td><%= link_to kb.tags, kb_path(kb) %></td>
        <td><%= link_to kb.title, kb_path(kb) %></td>
        <td><%= raw kb.content[0..100].gsub(/\n/,'<br />') %>...</td>
        <% if is_admin? %>
          <td>
            <%= link_to 'Edit', edit_kb_path(kb), :class => 'btn btn-mini' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if is_admin? %>
  <%= link_to 'New', new_kb_path, :class => 'btn btn-primary' %>
<% end %>

app/views/kbs/show.html.erb
<h1>/Note</h1>

<p>
  <b>Tags</b><br>
  <%= @kb.tags %>
</p>

<p>
  <b>Title</b><br>
  <%= @kb.title %>
</p>

<p>
  <b>Content</b><br>
  <%= raw @kb.content.gsub(/\n/,'<br />') %>
</p>

<div class="form-actions">
  <%= link_to 'Back', kbs_path, :class => 'btn'  %>
  <% if is_admin? %>
    <%= link_to 'Edit', edit_kb_path(@kb), :class => 'btn' %>
    <%= link_to 'Delete', kb_path(@kb), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <title>Kbase</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">Kbase</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Notes", kbs_path %></li>
          <% if is_admin? %>
            <li class="divider-vertical"></li>
            <li><%= link_to "Users", users_path %></li>
          <% end %>
        </ul>
      </div>
      <div class="nav pull-right">
        <ul class="nav">
          <li class="divider-vertical"></li>
          <form class="navbar-search" id="search">
            <input type="text" id="q" class="search-query span3"
             placeholder="Search" values="<%= params[:q] %>">
          </form>
          <li class="divider-vertical"></li>
          <% if current_user %>
            <li class="welcome"><%= link_to "#{current_user.email}", "#" %>
            <li class="divider-vertical"></li>
            <li><%= link_to "Log Out", logout_path %>
          <% else %>
            <li><%= link_to "Sign Up", signup_path %>
            <li class="divider-vertical"></li>
            <li><%= link_to "Log In", login_path %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <% flash.each do |name,msg| %>
    <div class="alert alert-<%= name == :notice ? 'success' : 'error' %>">
      <a class="close" data-dismiss="alert">&otimes;</a>
      <%= msg %>
    </div>
  <% end %>
  <div class="row">
    <div class="span10">
      <%= yield %>
    </div>
    <div class="span2">
      <div class="well sidebar-nav">
        <center> 
        <ul class="nav nav-list">  
          <li class="nav-header">Visitors</li>  
        </ul>  
        <script type="text/javascript" src="http://jg.revolvermaps.com/r.js"></script>
        <script type="text/javascript">rm_f1st('8','120','true','false','000000','6ll3l29icx4','true','ff0000');
        </script>
        <noscript>
        <applet codebase="http://rg.revolvermaps.com/j" code="core.RE" width="120" height="120" archive="g.jar">
          <param name="cabbase" value="g.cab" />
          <param name="r" value="true" />
          <param name="n" value="false" />
          <param name="i" value="6ll3l29icx4" />
          <param name="m" value="8" />
          <param name="s" value="120" />
          <param name="c" value="ff0000" />
          <param name="v" value="true" />
          <param name="b" value="000000" />
          <param name="rfc" value="true" />
        </applet>
        </noscript>
        </center>
      </div>
    </div>  
  </div>
</div>
</body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /User</legend>

    <%= f.input :email %>
    <% if is_admin? %>
      <%= f.input :role,
                  :as => :select,
                  :collection => ['member','admin']
      %>
    <% else %>
      <%= f.input :role, :as => :hidden, :input_html => {:value => 'member'} %>
    <% end %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>

    <%= f.button :submit, :label => "OK" %>

  </fieldset>
<% end %>

app/views/users/edit.html.erb
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Role</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.email, user_path(user) %></td>
        <td><%= user.role %></td>
        <td>
          <%= link_to 'Edit', edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', user_path(user), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_user_path, :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<h1>/User</h1>

<p>
  <b>Email</b><br>
  <%= @user.email %>
</p>

<p>
  <b>Role</b><br>
  <%= @user.role %>
</p>

<p>
  <b>Password digest</b><br>
  <%= @user.password_digest %>
</p>

<div class="form-actions">
  <%= link_to 'Back', users_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_user_path(@user), :class => 'btn' %>
  <%= link_to 'Delete', user_path(@user), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>